parameters:
    env(DATABASE_URL): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
    Microservices\Sample\:
        resource: '../src/*'
        exclude: '../src/{Entity,Kernel.php}'

framework:
    secret: '%env(APP_SECRET)%'

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        mappings:
            Sample:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Microservices\Sample\Entity'
